version: '3'

services:
  haproxy:
    image: haproxytech/haproxy-alpine:2.8
    container_name:  lb
    ports:
      - "80:80"
      - "8080:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

    depends_on:
      - web1
      - web2
      - web3
      - web4
      - web5
      - web6

  web1:
    image: nginx:latest
    container_name: nginx1
  web2:
    image: nginx:latest
    container_name: nginx2
  web3:
    image: nginx:latest
    container_name: nginx3
  web4:
    image: caddy:latest
    container_name: caddy1
  web5:
    image: caddy:latest
    container_name: caddy2
  web6:
    image: caddy:latest
    container_name: caddy3
    